#!/usr/bin/env python3
"""Train and export a legacy learned robot swept-pointcloud model.

The recommended architecture is deterministic FK/simulator robot point flow,
then a learned point-world model for scene response. This script is retained for
compatibility or for baseline experiments when no deterministic geometry source
is available.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from safety_module.robot_pointcloud_model import RobotSweptPointCloudModel, chamfer_distance  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train the legacy robot swept-pointcloud predictor.")
    parser.add_argument("--dataset", type=Path, required=True, help=".npz generated by collect_libero_robot_swept_dataset.py")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT / "outputs" / "robot_pointcloud_world_model",
    )
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--hidden-dim", type=int, default=512)
    parser.add_argument("--num-layers", type=int, default=4)
    parser.add_argument("--dropout", type=float, default=0.0)
    parser.add_argument(
        "--target-coverage-weight",
        type=float,
        default=3.0,
        help="Weight for target->prediction Chamfer term. Larger means fewer missed robot points.",
    )
    parser.add_argument("--val-fraction", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    return parser.parse_args()


def load_dataset(path: Path) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, dict]:
    data = np.load(path, allow_pickle=False)
    for key in ("states", "actions", "points"):
        if key not in data:
            raise ValueError(f"{path} is missing {key!r}")

    states = np.asarray(data["states"], dtype=np.float32)
    actions = np.asarray(data["actions"], dtype=np.float32)
    points = np.asarray(data["points"], dtype=np.float32)
    if states.ndim != 2:
        raise ValueError(f"states must have shape (N, S), got {states.shape}")
    if actions.ndim != 3:
        raise ValueError(f"actions must have shape (N, H, A), got {actions.shape}")
    if points.ndim != 3 or points.shape[-1] != 3:
        raise ValueError(f"points must have shape (N, P, 3), got {points.shape}")
    if not (len(states) == len(actions) == len(points)):
        raise ValueError("states, actions, and points must have the same sample count")

    metadata = {
        "state_mode": str(data["state_mode"]) if "state_mode" in data else "unknown",
        "task_name": str(data["task_name"]) if "task_name" in data else "unknown",
    }
    return torch.from_numpy(states), torch.from_numpy(actions), torch.from_numpy(points), metadata


def split_dataset(
    states: torch.Tensor,
    actions: torch.Tensor,
    points: torch.Tensor,
    val_fraction: float,
    seed: int,
) -> tuple[TensorDataset, TensorDataset]:
    n = states.shape[0]
    generator = torch.Generator().manual_seed(seed)
    perm = torch.randperm(n, generator=generator)
    val_count = int(round(n * val_fraction))
    val_count = min(max(val_count, 1 if n > 1 else 0), n - 1 if n > 1 else 0)
    val_idx = perm[:val_count]
    train_idx = perm[val_count:]
    return (
        TensorDataset(states[train_idx], actions[train_idx], points[train_idx]),
        TensorDataset(states[val_idx], actions[val_idx], points[val_idx]),
    )


def tensor_stats(x: torch.Tensor, dims) -> tuple[torch.Tensor, torch.Tensor]:
    mean = x.mean(dim=dims)
    std = x.std(dim=dims, unbiased=False)
    return mean, torch.clamp(std, min=1e-6)


def make_model(
    states: torch.Tensor,
    actions: torch.Tensor,
    points: torch.Tensor,
    args: argparse.Namespace,
) -> RobotSweptPointCloudModel:
    model = RobotSweptPointCloudModel(
        state_dim=states.shape[-1],
        action_horizon=actions.shape[1],
        action_dim=actions.shape[2],
        num_points=points.shape[1],
        hidden_dim=args.hidden_dim,
        num_layers=args.num_layers,
        dropout=args.dropout,
    )
    state_mean, state_std = tensor_stats(states, dims=0)
    action_mean, action_std = tensor_stats(actions, dims=0)
    point_mean, point_std = tensor_stats(points.reshape(-1, 3), dims=0)
    model.set_normalization(state_mean, state_std, action_mean, action_std, point_mean, point_std)
    return model


def run_epoch(
    model: RobotSweptPointCloudModel,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer | None,
    device: torch.device,
    target_coverage_weight: float,
) -> dict[str, float]:
    training = optimizer is not None
    model.train(training)
    total = 0
    loss_sum = 0.0
    p2t_sum = 0.0
    t2p_sum = 0.0

    for state, actions, target_points in loader:
        state = state.to(device=device, dtype=torch.float32)
        actions = actions.to(device=device, dtype=torch.float32)
        target_points = target_points.to(device=device, dtype=torch.float32)

        if training:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(training):
            pred_points = model(state, actions)
            loss, pred_to_target, target_to_pred = chamfer_distance(
                pred_points,
                target_points,
                target_coverage_weight=target_coverage_weight,
            )
            if training:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=10.0)
                optimizer.step()

        batch = state.shape[0]
        total += batch
        loss_sum += float(loss.detach().cpu()) * batch
        p2t_sum += float(pred_to_target.detach().cpu()) * batch
        t2p_sum += float(target_to_pred.detach().cpu()) * batch

    if total == 0:
        return {
            "loss": float("nan"),
            "pred_to_target": float("nan"),
            "target_to_pred": float("nan"),
        }
    denom = total
    return {
        "loss": loss_sum / denom,
        "pred_to_target": p2t_sum / denom,
        "target_to_pred": t2p_sum / denom,
    }


def export_torchscript(model: RobotSweptPointCloudModel, output_path: Path, device: torch.device) -> None:
    model.eval()
    example_state = torch.zeros(1, model.state_dim, device=device)
    example_actions = torch.zeros(1, model.action_horizon, model.action_dim, device=device)
    traced = torch.jit.trace(model, (example_state, example_actions), strict=True)
    traced.save(str(output_path))


def main() -> None:
    args = parse_args()
    if not 0.0 <= args.val_fraction < 1.0:
        raise ValueError("--val-fraction must be in [0, 1)")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    states, actions, points, metadata = load_dataset(args.dataset)
    train_set, val_set = split_dataset(states, actions, points, args.val_fraction, args.seed)
    train_loader = DataLoader(
        train_set,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        drop_last=False,
    )
    val_loader = DataLoader(
        val_set,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        drop_last=False,
    )

    device = torch.device(args.device)
    model = make_model(states, actions, points, args).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    best_val = float("inf")
    best_state = None
    for epoch in range(1, args.epochs + 1):
        train_metrics = run_epoch(model, train_loader, optimizer, device, args.target_coverage_weight)
        val_metrics = run_epoch(model, val_loader, None, device, args.target_coverage_weight)
        selection_loss = val_metrics["loss"] if np.isfinite(val_metrics["loss"]) else train_metrics["loss"]
        if selection_loss < best_val:
            best_val = selection_loss
            best_state = {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}
        print(
            "[epoch {epoch:04d}] train={train:.6f} val={val:.6f} "
            "val_target_to_pred={t2p:.6f} val_pred_to_target={p2t:.6f}".format(
                epoch=epoch,
                train=train_metrics["loss"],
                val=val_metrics["loss"],
                t2p=val_metrics["target_to_pred"],
                p2t=val_metrics["pred_to_target"],
            )
        )

    if best_state is not None:
        model.load_state_dict(best_state)

    ckpt_path = args.output_dir / "robot_pointcloud_model_checkpoint.pt"
    script_path = args.output_dir / "robot_pointcloud_model.pt"
    torch.save(
        {
            "model_state_dict": model.cpu().state_dict(),
            "state_dim": model.state_dim,
            "action_horizon": model.action_horizon,
            "action_dim": model.action_dim,
            "num_points": model.num_points,
            "hidden_dim": args.hidden_dim,
            "num_layers": args.num_layers,
            "dropout": args.dropout,
            "best_val_loss": best_val,
            "metadata": metadata,
        },
        ckpt_path,
    )
    model = model.to(device)
    export_torchscript(model, script_path, device)
    print(f"[done] saved checkpoint: {ckpt_path}")
    print(f"[done] saved TorchScript model: {script_path}")
    print(
        "[done] model signature: model(state: (B, {s}), actions: (B, {h}, {a})) -> points: (B, {p}, 3)".format(
            s=model.state_dim,
            h=model.action_horizon,
            a=model.action_dim,
            p=model.num_points,
        )
    )


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, ValueError) as exc:
        print(f"[error] {exc}", file=sys.stderr)
        sys.exit(1)
