"""Action-conditioned point world model for scene response prediction.

The model assumes robot geometry has already been generated by a deterministic
kinematic layer, e.g. URDF/FK or a simulator-exported TorchScript module. It
learns only how the current scene point cloud responds to the future robot
point flow.
"""

from __future__ import annotations

from typing import Any, Dict, Optional, Tuple, Union

import torch
import torch.nn as nn
import torch.nn.functional as F


TensorDict = Dict[str, torch.Tensor]


def _mlp(input_dim: int, hidden_dim: int, output_dim: int, num_layers: int) -> nn.Sequential:
    if num_layers < 2:
        raise ValueError("num_layers must be at least 2")
    layers: list[nn.Module] = []
    dim = input_dim
    for _ in range(num_layers - 1):
        layers.append(nn.Linear(dim, hidden_dim))
        layers.append(nn.GELU())
        dim = hidden_dim
    layers.append(nn.Linear(dim, output_dim))
    return nn.Sequential(*layers)


def normalize_robot_point_flow(robot_point_flow: torch.Tensor) -> torch.Tensor:
    """Return robot points as ``(B, H, R, 3)``.

    A single swept cloud ``(B, R, 3)`` is accepted as a one-step flow for
    compatibility, but callers should prefer time-indexed robot points.
    """

    if robot_point_flow.shape[-1] != 3:
        raise ValueError(f"robot_point_flow last dim must be 3, got {tuple(robot_point_flow.shape)}")
    if robot_point_flow.ndim == 3:
        return robot_point_flow[:, None]
    if robot_point_flow.ndim == 4:
        return robot_point_flow
    raise ValueError(f"robot_point_flow must have shape (B, R, 3) or (B, H, R, 3), got {tuple(robot_point_flow.shape)}")


def scene_robot_distance_features(
    scene_points: torch.Tensor,
    robot_point_flow: torch.Tensor,
    contact_radius: float,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Compute per-scene-point robot proximity features.

    Returns:
        min_dist: ``(B, H, N, 1)`` distance to the nearest robot point at each step.
        radial: ``(B, H, N, 1)`` smooth contact kernel ``exp(-d / radius)``.
    """

    robot_point_flow = normalize_robot_point_flow(robot_point_flow)
    if scene_points.ndim != 3 or scene_points.shape[-1] != 3:
        raise ValueError(f"scene_points must have shape (B, N, 3), got {tuple(scene_points.shape)}")
    if scene_points.shape[0] != robot_point_flow.shape[0]:
        raise ValueError("scene_points and robot_point_flow must have the same batch size")

    batch, horizon, robot_points, _ = robot_point_flow.shape
    scene_count = scene_points.shape[1]
    flat_scene = scene_points[:, None].expand(batch, horizon, scene_count, 3).reshape(batch * horizon, scene_count, 3)
    flat_robot = robot_point_flow.reshape(batch * horizon, robot_points, 3)
    min_dist = torch.cdist(flat_scene, flat_robot).amin(dim=-1).reshape(batch, horizon, scene_count, 1)
    radial = torch.exp(-min_dist / max(float(contact_radius), 1e-6))
    return min_dist, radial


class PointWorldModel(nn.Module):
    """Lightweight point model for affected masks and scene point flow.

    Inputs:
        scene_points: current non-robot scene points, ``(B, N, 3)``.
        robot_point_flow: deterministic future robot points, ``(B, H, R, 3)``.
        scene_features: optional per-point features such as RGB, ``(B, N, C)``.

    Outputs are a dict containing:
        mask_logits: ``(B, H, N)`` affected/contact logits.
        flow: ``(B, H, N, 3)`` scene point displacement from ``scene_points``.
        future_points: ``scene_points[:, None] + flow``.
        logvar: optional per-axis uncertainty for NLL training.
    """

    def __init__(
        self,
        scene_feature_dim: int = 0,
        hidden_dim: int = 256,
        num_layers: int = 4,
        contact_radius: float = 0.05,
        predict_flow: bool = True,
        predict_uncertainty: bool = False,
    ) -> None:
        super().__init__()
        if hidden_dim <= 0:
            raise ValueError("hidden_dim must be positive")
        self.scene_feature_dim = int(scene_feature_dim)
        self.hidden_dim = int(hidden_dim)
        self.contact_radius = float(contact_radius)
        self.predict_flow = bool(predict_flow)
        self.predict_uncertainty = bool(predict_uncertainty)

        scene_input_dim = 3 + self.scene_feature_dim
        self.scene_encoder = _mlp(scene_input_dim, hidden_dim, hidden_dim, num_layers=3)

        pair_input_dim = (
            hidden_dim  # local scene embedding
            + hidden_dim  # global scene context
            + 3  # xyz
            + self.scene_feature_dim
            + 2  # min distance and radial contact kernel
            + 3  # robot centroid relative to scene point
            + 3  # robot centroid displacement over chunk
            + 1  # normalized time
        )
        self.trunk = _mlp(pair_input_dim, hidden_dim, hidden_dim, num_layers=num_layers)
        self.mask_head = nn.Linear(hidden_dim, 1)
        if self.predict_flow:
            self.flow_head = nn.Linear(hidden_dim, 3)
        if self.predict_uncertainty:
            self.logvar_head = nn.Linear(hidden_dim, 3)

    def forward(
        self,
        scene_points: torch.Tensor,
        robot_point_flow: torch.Tensor,
        scene_features: Optional[torch.Tensor] = None,
    ) -> TensorDict:
        robot_point_flow = normalize_robot_point_flow(robot_point_flow)
        if scene_points.ndim != 3 or scene_points.shape[-1] != 3:
            raise ValueError(f"scene_points must have shape (B, N, 3), got {tuple(scene_points.shape)}")
        if scene_features is None:
            if self.scene_feature_dim:
                raise ValueError("scene_features is required when scene_feature_dim > 0")
            scene_input = scene_points
            scene_features_for_pair = scene_points.new_zeros((*scene_points.shape[:2], 0))
        else:
            if scene_features.shape[:2] != scene_points.shape[:2]:
                raise ValueError("scene_features must share the first two dims with scene_points")
            if scene_features.shape[-1] != self.scene_feature_dim:
                raise ValueError(
                    f"scene_features last dim must be {self.scene_feature_dim}, got {scene_features.shape[-1]}"
                )
            scene_input = torch.cat((scene_points, scene_features), dim=-1)
            scene_features_for_pair = scene_features

        batch, horizon, _, _ = robot_point_flow.shape
        scene_count = scene_points.shape[1]

        scene_embed = self.scene_encoder(scene_input)
        global_scene = scene_embed.amax(dim=1, keepdim=True)
        min_dist, radial = scene_robot_distance_features(scene_points, robot_point_flow, self.contact_radius)

        robot_centroid = robot_point_flow.mean(dim=2)
        robot_delta = robot_centroid - robot_centroid[:, :1]
        rel_centroid = robot_centroid[:, :, None, :] - scene_points[:, None, :, :]
        rel_delta = robot_delta[:, :, None, :].expand(batch, horizon, scene_count, 3)

        time = torch.linspace(
            0.0,
            1.0,
            horizon,
            device=scene_points.device,
            dtype=scene_points.dtype,
        ).view(1, horizon, 1, 1)
        time = time.expand(batch, horizon, scene_count, 1)

        scene_embed_h = scene_embed[:, None].expand(batch, horizon, scene_count, self.hidden_dim)
        global_h = global_scene[:, None].expand(batch, horizon, scene_count, self.hidden_dim)
        xyz_h = scene_points[:, None].expand(batch, horizon, scene_count, 3)
        feat_h = scene_features_for_pair[:, None].expand(batch, horizon, scene_count, self.scene_feature_dim)
        pair_features = torch.cat(
            (scene_embed_h, global_h, xyz_h, feat_h, min_dist, radial, rel_centroid, rel_delta, time),
            dim=-1,
        )

        hidden = self.trunk(pair_features.reshape(batch * horizon * scene_count, -1))
        mask_logits = self.mask_head(hidden).reshape(batch, horizon, scene_count)
        outputs: TensorDict = {"mask_logits": mask_logits}

        if self.predict_flow:
            flow = self.flow_head(hidden).reshape(batch, horizon, scene_count, 3)
        else:
            flow = scene_points.new_zeros(batch, horizon, scene_count, 3)
        outputs["flow"] = flow
        outputs["future_points"] = scene_points[:, None] + flow

        if self.predict_uncertainty:
            outputs["logvar"] = torch.clamp(
                self.logvar_head(hidden).reshape(batch, horizon, scene_count, 3),
                min=-10.0,
                max=5.0,
            )
        return outputs


def infer_target_flow(
    scene_points: torch.Tensor,
    target_future_points: Optional[torch.Tensor],
    target_flow: Optional[torch.Tensor],
) -> Optional[torch.Tensor]:
    if target_flow is not None:
        return target_flow
    if target_future_points is None:
        return None
    return target_future_points - scene_points[:, None]


def chamfer_hausdorff_loss(
    pred_points: torch.Tensor,
    target_points: torch.Tensor,
    target_coverage_weight: float = 1.0,
    hausdorff_weight: float = 0.1,
) -> Tuple[torch.Tensor, Dict[str, Any]]:
    """Loss for unordered future point clouds.

    Both tensors may be ``(B, N, 3)`` or ``(B, H, N, 3)``. The point counts do
    not need to match. This is the fallback when future scene point labels do
    not have fixed correspondence to the current scene points.
    """

    if pred_points.shape[-1] != 3 or target_points.shape[-1] != 3:
        raise ValueError("pred_points and target_points must end in xyz")
    if pred_points.ndim == 3:
        pred_points = pred_points[:, None]
    if target_points.ndim == 3:
        target_points = target_points[:, None]
    if pred_points.ndim != 4 or target_points.ndim != 4:
        raise ValueError("pred_points and target_points must have shape (B, N, 3) or (B, H, N, 3)")
    if pred_points.shape[:2] != target_points.shape[:2]:
        raise ValueError("pred_points and target_points must share batch and horizon dimensions")

    batch, horizon = pred_points.shape[:2]
    pred_flat = pred_points.reshape(batch * horizon, pred_points.shape[-2], 3)
    target_flat = target_points.reshape(batch * horizon, target_points.shape[-2], 3)
    distances = torch.cdist(pred_flat, target_flat)
    pred_nn = distances.amin(dim=2)
    target_nn = distances.amin(dim=1)
    chamfer = pred_nn.pow(2).mean() + float(target_coverage_weight) * target_nn.pow(2).mean()
    hausdorff = pred_nn.amax(dim=1).mean() + target_nn.amax(dim=1).mean()
    loss = chamfer + float(hausdorff_weight) * hausdorff
    return loss, {
        "chamfer_loss": chamfer.detach(),
        "hausdorff_loss": hausdorff.detach(),
        "unordered_loss": loss.detach(),
    }


def build_point_weights(
    scene_points: torch.Tensor,
    target_flow: Optional[torch.Tensor],
    target_mask: Optional[torch.Tensor],
    robot_point_flow: Optional[torch.Tensor],
    moving_threshold: float,
    moving_weight: float,
    near_robot_radius: float,
    near_robot_weight: float,
    contact_weight: float,
) -> torch.Tensor:
    if target_flow is not None:
        base_shape = target_flow.shape[:-1]
        device = target_flow.device
        dtype = target_flow.dtype
    elif target_mask is not None:
        base_shape = target_mask.shape
        device = target_mask.device
        dtype = target_mask.dtype
    elif robot_point_flow is not None:
        robot_point_flow = normalize_robot_point_flow(robot_point_flow)
        base_shape = (scene_points.shape[0], robot_point_flow.shape[1], scene_points.shape[1])
        device = scene_points.device
        dtype = scene_points.dtype
    else:
        base_shape = (scene_points.shape[0], 1, scene_points.shape[1])
        device = scene_points.device
        dtype = scene_points.dtype

    weights = torch.ones(base_shape, device=device, dtype=dtype)
    moving = None
    if target_flow is not None:
        moving = torch.linalg.norm(target_flow, dim=-1) > float(moving_threshold)
        weights = weights + moving.to(dtype) * float(moving_weight)
    if target_mask is not None:
        mask_bool = target_mask > 0.5
        moving = mask_bool if moving is None else (moving | mask_bool)
        weights = weights + mask_bool.to(dtype) * float(moving_weight)
    if robot_point_flow is not None:
        min_dist, radial = scene_robot_distance_features(scene_points, robot_point_flow, near_robot_radius)
        near = min_dist.squeeze(-1) < float(near_robot_radius)
        weights = weights + near.to(dtype) * float(near_robot_weight) + radial.squeeze(-1) * float(contact_weight)
        if moving is not None:
            weights = weights + (near & moving).to(dtype) * float(contact_weight)
    return weights


def point_world_model_loss(
    predictions: Union[TensorDict, torch.Tensor],
    scene_points: torch.Tensor,
    target_future_points: Optional[torch.Tensor] = None,
    target_flow: Optional[torch.Tensor] = None,
    target_mask: Optional[torch.Tensor] = None,
    target_occupancy: Optional[torch.Tensor] = None,
    robot_point_flow: Optional[torch.Tensor] = None,
    lambda_flow: float = 1.0,
    lambda_mask: float = 1.0,
    lambda_occ: float = 0.0,
    lambda_smooth: float = 0.05,
    lambda_unc: float = 0.0,
    moving_threshold: float = 0.01,
    moving_weight: float = 8.0,
    near_robot_radius: float = 0.06,
    near_robot_weight: float = 3.0,
    contact_weight: float = 5.0,
) -> Tuple[torch.Tensor, Dict[str, Any]]:
    """Weighted loss for affected mask and scene flow prediction.

    ``target_future_points``/``target_flow`` require fixed point
    correspondences. If correspondences are unavailable, train the mask here and
    use Chamfer/Hausdorff/occupancy losses outside this function for unordered
    future clouds.
    """

    if isinstance(predictions, torch.Tensor):
        pred_flow = predictions
        mask_logits = None
        logvar = None
        occupancy_logits = None
    else:
        pred_flow = predictions.get("flow")
        mask_logits = predictions.get("mask_logits")
        logvar = predictions.get("logvar")
        occupancy_logits = predictions.get("occupancy_logits")

    target_flow = infer_target_flow(scene_points, target_future_points, target_flow)
    if target_mask is None and target_flow is not None:
        target_mask = (torch.linalg.norm(target_flow, dim=-1) > float(moving_threshold)).to(target_flow.dtype)

    weights = build_point_weights(
        scene_points=scene_points,
        target_flow=target_flow,
        target_mask=target_mask,
        robot_point_flow=robot_point_flow,
        moving_threshold=moving_threshold,
        moving_weight=moving_weight,
        near_robot_radius=near_robot_radius,
        near_robot_weight=near_robot_weight,
        contact_weight=contact_weight,
    )
    weight_norm = torch.clamp(weights.mean(), min=1e-6)

    total = scene_points.new_tensor(0.0)
    metrics: Dict[str, Any] = {}

    if pred_flow is not None and target_flow is not None and lambda_flow:
        huber = F.huber_loss(pred_flow, target_flow, reduction="none").mean(dim=-1)
        flow_loss = (huber * weights).mean() / weight_norm
        total = total + float(lambda_flow) * flow_loss
        metrics["flow_loss"] = flow_loss.detach()
        with torch.no_grad():
            metrics["flow_l1"] = torch.abs(pred_flow - target_flow).mean()

    if pred_flow is not None and target_flow is not None and logvar is not None and lambda_unc:
        residual2 = (pred_flow - target_flow).pow(2)
        nll = 0.5 * (torch.exp(-logvar) * residual2 + logvar).mean(dim=-1)
        unc_loss = (nll * weights).mean() / weight_norm
        total = total + float(lambda_unc) * unc_loss
        metrics["uncertainty_nll"] = unc_loss.detach()

    if mask_logits is not None and target_mask is not None and lambda_mask:
        mask_loss = F.binary_cross_entropy_with_logits(
            mask_logits,
            target_mask.to(mask_logits.dtype),
            reduction="none",
        )
        mask_loss = (mask_loss * weights).mean() / weight_norm
        total = total + float(lambda_mask) * mask_loss
        metrics["mask_loss"] = mask_loss.detach()
        with torch.no_grad():
            pred_mask = torch.sigmoid(mask_logits) > 0.5
            metrics["mask_positive_rate"] = pred_mask.to(torch.float32).mean()

    if occupancy_logits is not None and target_occupancy is not None and lambda_occ:
        occ_loss = F.binary_cross_entropy_with_logits(occupancy_logits, target_occupancy.to(occupancy_logits.dtype))
        total = total + float(lambda_occ) * occ_loss
        metrics["occupancy_loss"] = occ_loss.detach()

    if pred_flow is not None and pred_flow.shape[1] >= 3 and lambda_smooth:
        second_diff = pred_flow[:, 2:] - 2.0 * pred_flow[:, 1:-1] + pred_flow[:, :-2]
        smooth_loss = second_diff.abs().mean()
        total = total + float(lambda_smooth) * smooth_loss
        metrics["smooth_loss"] = smooth_loss.detach()

    metrics["loss"] = total.detach()
    metrics["mean_point_weight"] = weights.mean().detach()
    return total, metrics
