"""PyTorch safety loss for robot point clouds against a precomputed safe-space SDF."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional, Tuple, Union

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


def load_safe_space_sdf(path: Union[str, Path]) -> Dict[str, np.ndarray]:
    """Load a safe-space SDF .npz generated by scripts/build_safe_space_sdf.py."""

    data = np.load(path)
    required = ("sdf_grid", "workspace_bounds", "voxel_size")
    missing = [name for name in required if name not in data]
    if missing:
        raise ValueError(f"{path} is missing required arrays: {missing}")

    sdf_grid = np.asarray(data["sdf_grid"], dtype=np.float32)
    if sdf_grid.ndim != 3:
        raise ValueError(f"sdf_grid must have shape (nx, ny, nz), got {sdf_grid.shape}")

    bounds = np.asarray(data["workspace_bounds"], dtype=np.float32)
    if bounds.shape != (6,):
        raise ValueError(f"workspace_bounds must have shape (6,), got {bounds.shape}")

    voxel_size = np.asarray(data["voxel_size"], dtype=np.float32)
    return {
        "sdf_grid": sdf_grid,
        "workspace_bounds": bounds,
        "voxel_size": voxel_size,
        "sdf_origin": np.asarray(
            data["sdf_origin"] if "sdf_origin" in data else [bounds[0], bounds[2], bounds[4]],
            dtype=np.float32,
        ),
    }


class SafetyLoss(nn.Module):
    """Penalize robot points whose SDF value is below a safety margin.

    Expected input shape is (..., 3), where the last dimension is world xyz.
    SDF convention:
        positive: inside safe space
        zero: safety boundary
        negative: obstacle or outside workspace
    """

    def __init__(
        self,
        sdf_grid: torch.Tensor,
        workspace_bounds: torch.Tensor,
        voxel_size: float,
        margin: float = 0.03,
        power: float = 2.0,
        reduction: str = "mean",
    ) -> None:
        super().__init__()
        if sdf_grid.ndim != 3:
            raise ValueError(f"sdf_grid must have shape (nx, ny, nz), got {tuple(sdf_grid.shape)}")
        if reduction not in {"mean", "sum", "none"}:
            raise ValueError(f"unsupported reduction: {reduction}")

        sdf_grid = sdf_grid.to(dtype=torch.float32)
        workspace_bounds = workspace_bounds.to(dtype=torch.float32)
        if workspace_bounds.shape != (6,):
            raise ValueError(
                f"workspace_bounds must have shape (6,), got {tuple(workspace_bounds.shape)}"
            )

        # grid_sample expects volumetric tensors as (N, C, D, H, W), i.e. z, y, x.
        grid_zyx = sdf_grid.permute(2, 1, 0).contiguous().unsqueeze(0).unsqueeze(0)
        self.register_buffer("sdf_grid_zyx", grid_zyx)
        self.register_buffer("workspace_bounds", workspace_bounds)
        self.register_buffer(
            "bounds_min",
            torch.stack((workspace_bounds[0], workspace_bounds[2], workspace_bounds[4])).to(dtype=torch.float32),
        )
        self.register_buffer(
            "bounds_max",
            torch.stack((workspace_bounds[1], workspace_bounds[3], workspace_bounds[5])).to(dtype=torch.float32),
        )
        self.voxel_size = float(voxel_size)
        self.margin = float(margin)
        self.power = float(power)
        self.reduction = reduction

    @classmethod
    def from_npz(
        cls,
        path: Union[str, Path],
        margin: float = 0.03,
        power: float = 2.0,
        reduction: str = "mean",
        device: Optional[Union[torch.device, str]] = None,
        dtype: torch.dtype = torch.float32,
    ) -> "SafetyLoss":
        data = load_safe_space_sdf(path)
        module = cls(
            sdf_grid=torch.as_tensor(data["sdf_grid"], dtype=dtype),
            workspace_bounds=torch.as_tensor(data["workspace_bounds"], dtype=dtype),
            voxel_size=float(np.asarray(data["voxel_size"]).item()),
            margin=margin,
            power=power,
            reduction=reduction,
        )
        if device is not None:
            module = module.to(device=device)
        return module

    def _center_lattice_bounds(self) -> Tuple[torch.Tensor, torch.Tensor]:
        dims_xyz = torch.tensor(
            [
                self.sdf_grid_zyx.shape[-1],
                self.sdf_grid_zyx.shape[-2],
                self.sdf_grid_zyx.shape[-3],
            ],
            dtype=self.bounds_min.dtype,
            device=self.bounds_min.device,
        )
        half = 0.5 * self.voxel_size
        first = self.bounds_min + half
        last = self.bounds_min + (dims_xyz - 0.5) * self.voxel_size
        return first, last

    def _normalized_grid_coords(self, points: torch.Tensor) -> torch.Tensor:
        first, last = self._center_lattice_bounds()
        denom = torch.clamp(last - first, min=1e-6)
        normalized = 2.0 * (points - first) / denom - 1.0
        return normalized

    def box_sdf(self, points: torch.Tensor) -> torch.Tensor:
        """Signed distance to the axis-aligned workspace box."""

        lower_violation = self.bounds_min - points
        upper_violation = points - self.bounds_max
        outside_delta = torch.maximum(torch.maximum(lower_violation, upper_violation), torch.zeros_like(points))
        outside_distance = torch.linalg.norm(outside_delta, dim=-1)

        inside_distance = torch.minimum(points - self.bounds_min, self.bounds_max - points).amin(dim=-1)
        outside = (outside_delta > 0).any(dim=-1)
        return torch.where(outside, -outside_distance, inside_distance)

    def query_sdf(self, points: torch.Tensor) -> torch.Tensor:
        """Differentiably query SDF at world-coordinate points with trilinear interpolation."""

        if points.shape[-1] != 3:
            raise ValueError(f"points last dimension must be 3, got {tuple(points.shape)}")
        original_shape = points.shape[:-1]
        flat_points = points.reshape(-1, 3).to(
            device=self.sdf_grid_zyx.device,
            dtype=self.sdf_grid_zyx.dtype,
        )

        grid_xyz = self._normalized_grid_coords(flat_points)
        # grid_sample order is x, y, z even though the tensor layout is D, H, W.
        sample_grid = grid_xyz.view(1, -1, 1, 1, 3)
        sampled = F.grid_sample(
            self.sdf_grid_zyx,
            sample_grid,
            mode="bilinear",
            padding_mode="border",
            align_corners=True,
        ).view(-1)

        # Enforce the continuous workspace boundary exactly; outside the box is unsafe.
        sampled = torch.minimum(sampled, self.box_sdf(flat_points))
        return sampled.reshape(original_shape)

    def forward(
        self,
        points: torch.Tensor,
        return_info: bool = False,
    ) -> Union[torch.Tensor, Tuple[torch.Tensor, Dict[str, Any]]]:
        sdf = self.query_sdf(points)
        violation = torch.relu(self.margin - sdf)
        if self.power == 1.0:
            per_point = violation
        else:
            per_point = violation.pow(self.power)

        if self.reduction == "mean":
            loss = per_point.mean()
        elif self.reduction == "sum":
            loss = per_point.sum()
        else:
            loss = per_point

        if not return_info:
            return loss

        with torch.no_grad():
            info: Dict[str, Any] = {
                "min_sdf": sdf.min(),
                "mean_sdf": sdf.mean(),
                "unsafe_ratio": (sdf < 0.0).to(torch.float32).mean(),
                "margin_violation_ratio": (sdf < self.margin).to(torch.float32).mean(),
                "max_violation": violation.max(),
            }
        return loss, info
